<nav class="navbar navbar-default justify-content-between">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Resorts World Sentosa</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-star"></span> Favorite Attraction</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-lock"></span> Block Tickets</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-star"></span> About RWS</a></li>


        </ul>
        <div class="navbar-form pull-right">

            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </div>
</nav>